// Copyright 2016 Richard Hawkins (hurricanerix@gmail.com)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package templates

const gmxFile = `<!--This Document is generated by pyxel2gm, if you edit it by hand then you do so at your own risk!-->
<sprite>
  <type>0</type>
  <xorig>10</xorig>
  <yorigin>5</yorigin>
  <colkind>2</colkind>
  <coltolerance>0</coltolerance>
  <sepmasks>0</sepmasks>
  <bboxmode>0</bboxmode>
  <bbox_left>0</bbox_left>
  <bbox_right>19</bbox_right>
  <bbox_top>0</bbox_top>
  <bbox_bottom>9</bbox_bottom>
  <HTile>0</HTile>
  <VTile>0</VTile>
  <TextureGroups>
    <TextureGroup0>0</TextureGroup0>
  </TextureGroups>
  <For3D>0</For3D>
  <width>20</width>
  <height>10</height>
  <frames>
    <frame index="0">images\spr_bullet_0.png</frame>
  </frames>
</sprite>`
